version: "3.6"
   
services:
  postgresuser:
    image: "postgres:11"
    volumes:
      - ./pgdata/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=quanghuy
      - POSTGRES_PASSWORD=12345678  
      - POSTGRES_DB=montoring
    env_file:
      - ./nginxsite/.env
    networks:
      - nginx
  mongo:
    image: "mongo:latest"
    container_name: mongodb
    volumes:
      - ./mongodb_data_container:/data/db
    ports:
      - "27018:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=quanghuy
      - MONGO_INITDB_ROOT_PASSWORD=12345678
      - MONGO_INITDB_DATABASE=app
    env_file:
      - ./nginxsite/.env
    networks:
      - nginx

  collectors:
    build:
      context: ./collectors
      dockerfile: Dockerfile.Web
    restart: always
    volumes:
      - ./collectors:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresuser
    networks:
      - nginx
    env_file:
      - ./collectors/.env
    
  nginxsite:
    build:
      context: ./nginxsite
      dockerfile: Dockerfile.Web
    restart: always
    volumes:
      - ./nginxsite:/app
    ports:
      - "8001:8001"
    depends_on:
      - postgresuser
      - mongo
    networks:
      - nginx
    env_file:
      - ./nginxsite/.env
        
volumes:
  mongodb_data_container:
    driver: local 
  pgdata:
    driver: local

      
networks:
  nginx:
    driver: bridge
